import { Session } from "next-auth";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Header from "~/componets/header";
import ProfileCarousel from "~/componets/profileCarousel";

export default function Home() {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Sleepingtree's Season of Discvery Prep</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#63536f] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Sleepingtree's{" "}
            <span className="text-[hsl(62,65%,70%)]">Season of Discvery </span>{" "}
            Prep
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <div
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              onClick={() => void signIn()}
            >
              <h3 className="text-2xl font-bold">Step one Login →</h3>
              <div className="text-lg">
                you will need to have a discord account
              </div>
            </div>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/profile/edit"
            >
              <h3 className="text-2xl font-bold">Secound Step →</h3>
              <div className="text-lg">Create/edit your profile</div>
            </Link>
          </div>
          <AuthShowcase sessionData={sessionData} />
          <div className="flex flex-row items-center gap-2">
            <ProfileCarousel />
          </div>
        </div>
      </main>
    </>
  );
}

function AuthShowcase({ sessionData }: { sessionData: Session | null }) {
  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <div className="text-center text-2xl text-blue-900">
        <div>
          {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        </div>
        <div></div>
      </div>
    </div>
  );
}
